name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint --if-present
        continue-on-error: true

      - name: Run tests
        run: npm run test --if-present
        continue-on-error: true

      - name: Build project
        run: npm run build

      - name: Type check
        run: npm run type-check --if-present
        continue-on-error: true

      - name: Check build output
        run: |
          if [ -d ".next" ]; then
            echo "✅ Next.js build successful"
            ls -la .next
          elif [ -d "dist" ]; then
            echo "✅ Build output found in dist/"
            ls -la dist
          elif [ -d "build" ]; then
            echo "✅ Build output found in build/"
            ls -la build
          else
            echo "⚠️ No standard build output directory found"
          fi

  # Optional: Add deployment status check
  deployment-status:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test-and-build
    
    steps:
      - name: Deployment Info
        run: |
          echo "🚀 Deployment will be handled automatically by Vercel"
          echo "Check your Vercel dashboard for deployment status"
          echo "Project: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"